In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
pd.set_option('display.max_columns', None)

In [2]:
import folium
import mapclassify
from matplotlib import pyplot as plt

In [3]:
np_address = pd.read_csv("~/Downloads/aidatalab/shape_mapping.csv")
np_address["County"] = np_address["County"].astype(str).str[:5]
np_address

,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County,County_Name
0,1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13121,Fulton
1,1003104670,DODD,JOHN,M,2501 N PATTERSON ST,NaN,VALDOSTA,31602,NP,NaN,7/18/2011,RN117801,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13027,Brooks
2,1003128240,SARNO,JENNIFER,F,780 CANTON RD NE,SUITE 400,MARIETTA,30060,ACNP-BC,NaN,7/3/2010,177164,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13067,Cobb
3,1003222191,SAUCEDO,ISRAEL,M,417 W 3RD AVE,NaN,ALBANY,31701,"APRN, FN",6/29/2022,7/9/2014,RN170526,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,13095,Dougherty
4,1003280975,SHUMAKER-KIRK,CHARVETTE,F,600 CELEBRATE LIFE PKWY,NaN,NEWNAN,30265,NP-C,5/30/2023,11/16/2015,RN193221,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13077,Coweta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14462,1982088340,STONE,SARAH,F,3278 MITCHELL BLVD,NaN,MOODY AFB,31699,APRN-CNP,NaN,7/16/2015,RN176410,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13185,Lowndes
14463,1982210860,VINES,KRISTI,F,10692 MEDLOCK BRIDGE RD,NaN,JOHNS CREEK,30097,WHNP,9/16/2020,9/16/2020,RN255722,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13121,Fulton
14464,1982679189,KINNEY,KIMBERLY,F,5354 REYNOLDS ST STE 422,NaN,SAVANNAH,31405,"RN, NP",NaN,2/21/2006,24164385,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,13051,Chatham
14465,1992235469,CHAPMAN,NIJAH,F,2665 N DECATUR RD STE 255,NaN,DECATUR,30033,WHNP,NaN,6/15/2017,RN228375,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,13089,De Kalb
14466,1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,13067,Cobb

In [4]:
georgia = gpd.read_file("~/Downloads/aidatalab/cb_2024_13_bg_500k/cb_2024_13_bg_500k.shp")
georgia['COUNTYFP'] = '13' + georgia['COUNTYFP'].astype(str).str.zfill(3)
georgia = georgia.rename(columns={'COUNTYFP': 'County'})
georgia

,STATEFP,County,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry
0,13,13245,000300,1,1500000US132450003001,132450003001,1,Block Group 1,BG,990198,145569,"POLYGON ((-81.99436 33.47647, -81.99133 33.483..."
1,13,13089,023108,1,1500000US130890231081,130890231081,1,Block Group 1,BG,2070675,10004,"POLYGON ((-84.23738 33.75583, -84.23196 33.752..."
2,13,13135,050539,2,1500000US131350505392,131350505392,2,Block Group 2,BG,509055,0,"POLYGON ((-84.09713 33.94314, -84.09227 33.946..."
3,13,13179,010202,3,1500000US131790102023,131790102023,3,Block Group 3,BG,545751,0,"POLYGON ((-81.61084 31.8225, -81.60516 31.8217..."
4,13,13135,050448,2,1500000US131350504482,131350504482,2,Block Group 2,BG,434074,0,"POLYGON ((-84.18314 33.90831, -84.18226 33.908..."
...,...,...,...,...,...,...,...,...,...,...,...,...
7436,13,13067,030352,1,1500000US130670303521,130670303521,1,Block Group 1,BG,4228718,188812,"POLYGON ((-84.43778 33.94244, -84.43452 33.943..."
7437,13,13153,021205,1,1500000US131530212051,131530212051,1,Block Group 1,BG,7061124,14381,"POLYGON ((-83.72976 32.49794, -83.7295 32.4979..."
7438,13,13277,960800,1,1500000US132779608001,132779608001,1,Block Group 1,BG,83436253,2756048,"POLYGON ((-83.65318 31.37544, -83.65307 31.376..."
7439,13,13131,950401,1,1500000US131319504011,131319504011,1,Block Group 1,BG,40837522,812148,"POLYGON ((-84.23048 30.98703, -84.20872 30.986..."
7440,13,13107,970401,1,1500000US131079704011,131079704011,1,Block Group 1,BG,116303308,1081954,"POLYGON ((-82.49943 32.68634, -82.47076 32.710..."

In [5]:
merged = georgia.merge(np_address, on='County', how='right')
merged

,STATEFP,County,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County_Name
0,13,13121,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,"POLYGON ((-84.38732 33.77509, -84.38465 33.774...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
1,13,13121,011301,1,1500000US131210113011,131210113011,1,Block Group 1,BG,984978.0,0.0,"POLYGON ((-84.46831 33.69784, -84.46836 33.698...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
2,13,13121,010307,3,1500000US131210103073,131210103073,3,Block Group 3,BG,1054531.0,10232.0,"POLYGON ((-84.55538 33.63506, -84.55233 33.635...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
3,13,13121,006100,2,1500000US131210061002,131210061002,2,Block Group 2,BG,463240.0,0.0,"POLYGON ((-84.44512 33.73089, -84.44512 33.733...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
4,13,13121,004100,2,1500000US131210041002,131210041002,2,Block Group 2,BG,312097.0,0.0,"POLYGON ((-84.43392 33.74236, -84.43358 33.743...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4364222,13,13067,030343,3,1500000US130670303433,130670303433,3,Block Group 3,BG,1090175.0,39977.0,"POLYGON ((-84.41876 34.0445, -84.41831 34.0450...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb
4364223,13,13067,030337,1,1500000US130670303371,130670303371,1,Block Group 1,BG,1571956.0,68790.0,"POLYGON ((-84.40258 33.99384, -84.39456 33.992...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb
4364224,13,13067,030273,2,1500000US130670302732,130670302732,2,Block Group 2,BG,817640.0,9182.0,"POLYGON ((-84.59282 34.06132, -84.58954 34.065...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb
4364225,13,13067,030235,4,1500000US130670302354,130670302354,4,Block Group 4,BG,2345546.0,5779.0,"POLYGON ((-84.70304 33.94043, -84.69364 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb
4364226,13,13067,030352,1,1500000US130670303521,130670303521,1,Block Group 1,BG,4228718.0,188812.0,"POLYGON ((-84.43778 33.94244, -84.43452 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb

In [6]:
# Count number of NPs per county and NP type, but keep all columns
merged['count'] = merged.groupby(['County_Name', 'NP_Type_Grouped'])['NPI'].transform('count')
merged

,STATEFP,County,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County_Name,count
0,13,13121,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,"POLYGON ((-84.38732 33.77509, -84.38465 33.774...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0
1,13,13121,011301,1,1500000US131210113011,131210113011,1,Block Group 1,BG,984978.0,0.0,"POLYGON ((-84.46831 33.69784, -84.46836 33.698...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0
2,13,13121,010307,3,1500000US131210103073,131210103073,3,Block Group 3,BG,1054531.0,10232.0,"POLYGON ((-84.55538 33.63506, -84.55233 33.635...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0
3,13,13121,006100,2,1500000US131210061002,131210061002,2,Block Group 2,BG,463240.0,0.0,"POLYGON ((-84.44512 33.73089, -84.44512 33.733...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0
4,13,13121,004100,2,1500000US131210041002,131210041002,2,Block Group 2,BG,312097.0,0.0,"POLYGON ((-84.43392 33.74236, -84.43358 33.743...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4364222,13,13067,030343,3,1500000US130670303433,130670303433,3,Block Group 3,BG,1090175.0,39977.0,"POLYGON ((-84.41876 34.0445, -84.41831 34.0450...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0
4364223,13,13067,030337,1,1500000US130670303371,130670303371,1,Block Group 1,BG,1571956.0,68790.0,"POLYGON ((-84.40258 33.99384, -84.39456 33.992...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0
4364224,13,13067,030273,2,1500000US130670302732,130670302732,2,Block Group 2,BG,817640.0,9182.0,"POLYGON ((-84.59282 34.06132, -84.58954 34.065...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0
4364225,13,13067,030235,4,1500000US130670302354,130670302354,4,Block Group 4,BG,2345546.0,5779.0,"POLYGON ((-84.70304 33.94043, -84.69364 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0
4364226,13,13067,030352,1,1500000US130670303521,130670303521,1,Block Group 1,BG,4228718.0,188812.0,"POLYGON ((-84.43778 33.94244, -84.43452 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0

## aggregating

In [7]:
# Count number of NPs per county
merged['NP_count'] = merged.groupby('County_Name')['NPI'].transform('count')
merged

,STATEFP,County,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County_Name,count,NP_count
0,13,13121,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,"POLYGON ((-84.38732 33.77509, -84.38465 33.774...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0,1739166.0
1,13,13121,011301,1,1500000US131210113011,131210113011,1,Block Group 1,BG,984978.0,0.0,"POLYGON ((-84.46831 33.69784, -84.46836 33.698...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0,1739166.0
2,13,13121,010307,3,1500000US131210103073,131210103073,3,Block Group 3,BG,1054531.0,10232.0,"POLYGON ((-84.55538 33.63506, -84.55233 33.635...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0,1739166.0
3,13,13121,006100,2,1500000US131210061002,131210061002,2,Block Group 2,BG,463240.0,0.0,"POLYGON ((-84.44512 33.73089, -84.44512 33.733...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0,1739166.0
4,13,13121,004100,2,1500000US131210041002,131210041002,2,Block Group 2,BG,312097.0,0.0,"POLYGON ((-84.43392 33.74236, -84.43358 33.743...",1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton,169026.0,1739166.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4364222,13,13067,030343,3,1500000US130670303433,130670303433,3,Block Group 3,BG,1090175.0,39977.0,"POLYGON ((-84.41876 34.0445, -84.41831 34.0450...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0,511974.0
4364223,13,13067,030337,1,1500000US130670303371,130670303371,1,Block Group 1,BG,1571956.0,68790.0,"POLYGON ((-84.40258 33.99384, -84.39456 33.992...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0,511974.0
4364224,13,13067,030273,2,1500000US130670302732,130670302732,2,Block Group 2,BG,817640.0,9182.0,"POLYGON ((-84.59282 34.06132, -84.58954 34.065...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0,511974.0
4364225,13,13067,030235,4,1500000US130670302354,130670302354,4,Block Group 4,BG,2345546.0,5779.0,"POLYGON ((-84.70304 33.94043, -84.69364 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0,511974.0
4364226,13,13067,030352,1,1500000US130670303521,130670303521,1,Block Group 1,BG,4228718.0,188812.0,"POLYGON ((-84.43778 33.94244, -84.43452 33.943...",1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb,15390.0,511974.0

In [8]:
georgia_agg = georgia.dissolve(by='County', as_index=False)
merged = georgia_agg.merge(np_address, on='County', how='right')
merged

,County,geometry,STATEFP,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County_Name
0,13121,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",13,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
1,13027,"MULTIPOLYGON (((-83.73917 30.77797, -83.73927 ...",13,960400,3,1500000US130279604003,130279604003,3,Block Group 3,BG,1350973.0,0.0,1003104670,DODD,JOHN,M,2501 N PATTERSON ST,NaN,VALDOSTA,31602,NP,NaN,7/18/2011,RN117801,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Brooks
2,13067,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",13,031512,4,1500000US130670315124,130670315124,4,Block Group 4,BG,3908399.0,0.0,1003128240,SARNO,JENNIFER,F,780 CANTON RD NE,SUITE 400,MARIETTA,30060,ACNP-BC,NaN,7/3/2010,177164,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Cobb
3,13095,"POLYGON ((-84.14092 31.44041, -84.14112 31.440...",13,001500,3,1500000US130950015003,130950015003,3,Block Group 3,BG,731403.0,0.0,1003222191,SAUCEDO,ISRAEL,M,417 W 3RD AVE,NaN,ALBANY,31701,"APRN, FN",6/29/2022,7/9/2014,RN170526,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Dougherty
4,13077,"POLYGON ((-84.82473 33.22347, -84.82944 33.223...",13,170200,2,1500000US130771702002,130771702002,2,Block Group 2,BG,7638326.0,10381.0,1003280975,SHUMAKER-KIRK,CHARVETTE,F,600 CELEBRATE LIFE PKWY,NaN,NEWNAN,30265,NP-C,5/30/2023,11/16/2015,RN193221,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Coweta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14462,13185,"POLYGON ((-83.46716 30.76463, -83.46377 30.763...",13,010404,1,1500000US131850104041,131850104041,1,Block Group 1,BG,710720.0,0.0,1982088340,STONE,SARAH,F,3278 MITCHELL BLVD,NaN,MOODY AFB,31699,APRN-CNP,NaN,7/16/2015,RN176410,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Lowndes
14463,13121,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",13,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,1982210860,VINES,KRISTI,F,10692 MEDLOCK BRIDGE RD,NaN,JOHNS CREEK,30097,WHNP,9/16/2020,9/16/2020,RN255722,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
14464,13051,"POLYGON ((-81.28873 31.96897, -81.28754 31.974...",13,003601,2,1500000US130510036012,130510036012,2,Block Group 2,BG,577431.0,0.0,1982679189,KINNEY,KIMBERLY,F,5354 REYNOLDS ST STE 422,NaN,SAVANNAH,31405,"RN, NP",NaN,2/21/2006,24164385,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Chatham
14465,13089,"POLYGON ((-84.32945 33.64779, -84.33586 33.647...",13,023108,1,1500000US130890231081,130890231081,1,Block Group 1,BG,2070675.0,10004.0,1992235469,CHAPMAN,NIJAH,F,2665 N DECATUR RD STE 255,NaN,DECATUR,30033,WHNP,NaN,6/15/2017,RN228375,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,De Kalb
14466,13067,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",13,031512,4,1500000US130670315124,130670315124,4,Block Group 4,BG,3908399.0,0.0,1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb

In [9]:
merged['County'].nunique()

157

In [10]:
merged = gpd.GeoDataFrame(merged, geometry='geometry', crs="EPSG:4269")  # or 4326 if needed
merged

,County,geometry,STATEFP,TRACTCE,BLKGRPCE,GEOIDFQ,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,NPI,Last_Name,First_Name,Sex,Street1,Street2,City,ZIP,Credentials,Certification_Date,Enumeration_Date,License_Number,NP_Type_Grouped,Taxonomy_Code,Taxonomy_Description,Medicare_Supplier_Type,Primary_Tax,Medicare_Specialty_Code,County_Name
0,13121,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",13,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,1003095977,NICHOLAS,TRACY,F,1968 PEACHTREE RD NW,PIEDMONT HO,ATLANTA,30309,NP,NaN,10/29/2007,185022,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
1,13027,"MULTIPOLYGON (((-83.73917 30.77797, -83.73927 ...",13,960400,3,1500000US130279604003,130279604003,3,Block Group 3,BG,1350973.0,0.0,1003104670,DODD,JOHN,M,2501 N PATTERSON ST,NaN,VALDOSTA,31602,NP,NaN,7/18/2011,RN117801,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Brooks
2,13067,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",13,031512,4,1500000US130670315124,130670315124,4,Block Group 4,BG,3908399.0,0.0,1003128240,SARNO,JENNIFER,F,780 CANTON RD NE,SUITE 400,MARIETTA,30060,ACNP-BC,NaN,7/3/2010,177164,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Cobb
3,13095,"POLYGON ((-84.14092 31.44041, -84.14112 31.440...",13,001500,3,1500000US130950015003,130950015003,3,Block Group 3,BG,731403.0,0.0,1003222191,SAUCEDO,ISRAEL,M,417 W 3RD AVE,NaN,ALBANY,31701,"APRN, FN",6/29/2022,7/9/2014,RN170526,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Dougherty
4,13077,"POLYGON ((-84.82473 33.22347, -84.82944 33.223...",13,170200,2,1500000US130771702002,130771702002,2,Block Group 2,BG,7638326.0,10381.0,1003280975,SHUMAKER-KIRK,CHARVETTE,F,600 CELEBRATE LIFE PKWY,NaN,NEWNAN,30265,NP-C,5/30/2023,11/16/2015,RN193221,Acute Care NP,363LA2100X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Coweta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14462,13185,"POLYGON ((-83.46716 30.76463, -83.46377 30.763...",13,010404,1,1500000US131850104041,131850104041,1,Block Group 1,BG,710720.0,0.0,1982088340,STONE,SARAH,F,3278 MITCHELL BLVD,NaN,MOODY AFB,31699,APRN-CNP,NaN,7/16/2015,RN176410,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Lowndes
14463,13121,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",13,001205,2,1500000US131210012052,131210012052,2,Block Group 2,BG,134688.0,0.0,1982210860,VINES,KRISTI,F,10692 MEDLOCK BRIDGE RD,NaN,JOHNS CREEK,30097,WHNP,9/16/2020,9/16/2020,RN255722,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,Fulton
14464,13051,"POLYGON ((-81.28873 31.96897, -81.28754 31.974...",13,003601,2,1500000US130510036012,130510036012,2,Block Group 2,BG,577431.0,0.0,1982679189,KINNEY,KIMBERLY,F,5354 REYNOLDS ST STE 422,NaN,SAVANNAH,31405,"RN, NP",NaN,2/21/2006,24164385,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Chatham
14465,13089,"POLYGON ((-84.32945 33.64779, -84.33586 33.647...",13,023108,1,1500000US130890231081,130890231081,1,Block Group 1,BG,2070675.0,10004.0,1992235469,CHAPMAN,NIJAH,F,2665 N DECATUR RD STE 255,NaN,DECATUR,30033,WHNP,NaN,6/15/2017,RN228375,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,Y,50,De Kalb
14466,13067,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",13,031512,4,1500000US130670315124,130670315124,4,Block Group 4,BG,3908399.0,0.0,1992352728,PASCAL,SERENA,F,574 CHURCH ST NE,NaN,MARIETTA,30060,NP,5/16/2024,8/26/2019,421397,OBGYN/Womens Health NP,363LW0102X,Physician Assistants & Advanced Practice Nursi...,Nurse Practitioner,N,50,Cobb

In [11]:
import geopandas as gpd
import pandas as pd

# 1. Define specialties
specialties = [
    "Acute Care NP",
    "Adult/Gero NP",
    "Community/Occupational/School NP",
    "Critical Care NP",
    "Family/Primary Care NP",
    "Neonatal NP",
    "Neonatal Critical Care NP",
    "OBGYN/Womens Health NP",
    "Pediatrics NP",
    "Pediatrics Critical Care NP",
    "Psych/Mental Health NP",
    "NP, No Subspecialty Noted"
]

# 2. Count NPs per county and specialty
county_specialty_counts = (
    merged
    .groupby(["County_Name", "NP_Type_Grouped"])
    .size()
    .reset_index(name="count")
)

# 3. Pivot to wide format
pivot = (
    county_specialty_counts
    .pivot(index="County_Name", columns="NP_Type_Grouped", values="count")
    .fillna(0)
)

# 4. Ensure all specialties exist
for s in specialties:
    if s not in pivot.columns:
        pivot[s] = 0
pivot = pivot[specialties]

# 5. Add total NP count
pivot["NP Count"] = pivot.sum(axis=1)

# 6. Merge counts into GeoDataFrame
# Assume np_address is a GeoDataFrame with geometry column
# Keep only unique geometry per county
county_geometry = merged[["County_Name", "geometry"]].drop_duplicates(subset="County_Name")

# Merge without changing the geometry
final = county_geometry.merge(pivot, left_on="County_Name", right_index=True, how="left")

# Fill missing NP counts with 0
final[specialties + ["NP Count"]] = final[specialties + ["NP Count"]].fillna(0)

# 7. Rename for final CSV
final = final.rename(columns={"County_Name": "County", "geometry": "Shape"})

In [12]:
final

,County,Shape,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted",NP Count
0,Fulton,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",197.0,184.0,2.0,17.0,958.0,28.0,10.0,75.0,185.0,10.0,97.0,264.0,2027.0
1,Brooks,"MULTIPOLYGON (((-83.73917 30.77797, -83.73927 ...",1.0,1.0,0.0,0.0,11.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,18.0
2,Cobb,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",76.0,64.0,0.0,7.0,544.0,6.0,1.0,30.0,68.0,1.0,75.0,126.0,998.0
3,Dougherty,"POLYGON ((-84.14092 31.44041, -84.14112 31.440...",5.0,12.0,0.0,3.0,131.0,6.0,0.0,4.0,0.0,0.0,7.0,19.0,187.0
4,Coweta,"POLYGON ((-84.82473 33.22347, -84.82944 33.223...",13.0,9.0,0.0,1.0,101.0,1.0,1.0,2.0,4.0,0.0,7.0,21.0,160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5508,Lincoln,"POLYGON ((-82.31185 33.69808, -82.31642 33.697...",0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
5514,Randolph,"POLYGON ((-84.57033 31.76066, -84.56946 31.757...",0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0
5893,Screven,"POLYGON ((-81.67897 32.54814, -81.68099 32.548...",0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0
6038,Jasper,"POLYGON ((-83.82546 33.2203, -83.82369 33.2217...",0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
8967,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [13]:
final['County'].nunique()

156

In [14]:
#make all int
# List of NP count columns
np_count_cols = [
    "Acute Care NP",
    "Adult/Gero NP",
    "Community/Occupational/School NP",
    "Critical Care NP",
    "Family/Primary Care NP",
    "Neonatal NP",
    "Neonatal Critical Care NP",
    "OBGYN/Womens Health NP",
    "Pediatrics NP",
    "Pediatrics Critical Care NP",
    "Psych/Mental Health NP",
    "NP, No Subspecialty Noted",
    "NP Count"
]

# Fill NaNs with 0 and convert to int
final[np_count_cols] = final[np_count_cols].fillna(0).astype(int)

final = final[['County',
               'Shape',
               'NP Count',
                'Acute Care NP',
                'Adult/Gero NP',
                'Community/Occupational/School NP',
                'Critical Care NP',
                'Family/Primary Care NP',
                'Neonatal NP',
                'Neonatal Critical Care NP',
                'OBGYN/Womens Health NP',
                'Pediatrics NP',
                'Pediatrics Critical Care NP',
                'Psych/Mental Health NP',
                'NP, No Subspecialty Noted'
              ]]
final

,County,Shape,NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted"
0,Fulton,"POLYGON ((-84.55688 33.52849, -84.56629 33.526...",2027,197,184,2,17,958,28,10,75,185,10,97,264
1,Brooks,"MULTIPOLYGON (((-83.73917 30.77797, -83.73927 ...",18,1,1,0,0,11,0,0,0,2,0,1,2
2,Cobb,"POLYGON ((-84.6844 33.80587, -84.69426 33.806,...",998,76,64,0,7,544,6,1,30,68,1,75,126
3,Dougherty,"POLYGON ((-84.14092 31.44041, -84.14112 31.440...",187,5,12,0,3,131,6,0,4,0,0,7,19
4,Coweta,"POLYGON ((-84.82473 33.22347, -84.82944 33.223...",160,13,9,0,1,101,1,1,2,4,0,7,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5508,Lincoln,"POLYGON ((-82.31185 33.69808, -82.31642 33.697...",2,0,0,0,0,2,0,0,0,0,0,0,0
5514,Randolph,"POLYGON ((-84.57033 31.76066, -84.56946 31.757...",6,0,0,0,0,4,0,0,0,0,0,0,2
5893,Screven,"POLYGON ((-81.67897 32.54814, -81.68099 32.548...",6,0,0,0,0,5,0,0,0,0,0,0,1
6038,Jasper,"POLYGON ((-83.82546 33.2203, -83.82369 33.2217...",3,0,0,0,0,3,0,0,0,0,0,0,0
8967,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",1,0,0,0,0,1,0,0,0,0,0,0,0

In [15]:
missing_counties = pd.DataFrame({
    "County": ["13263", "13265", "13301"],
    "County_Name": ["Talbot", "Taliaferro", "Warren"]
})

georgia_agg = georgia.dissolve(by='County', as_index=False)

# 4. Replace FIPS codes with county names for only the missing counties
georgia_agg = georgia_agg.merge(missing_counties, on='County', how='left')
georgia_agg['County'] = georgia_agg['County_Name'].combine_first(georgia_agg['County'])
georgia_agg = georgia_agg.drop(columns=['County_Name'])

# 5. Get shapes only for the missing counties
missing_shapes = georgia_agg[georgia_agg['County'].isin(missing_counties['County_Name'])][['County', 'geometry']]
missing_shapes = missing_shapes.rename(columns={'geometry': 'Shape'})

# 6. Add NP count columns with zeros for only missing counties
np_count_cols = [
    'NP Count',
    'Acute Care NP',
    'Adult/Gero NP',
    'Community/Occupational/School NP',
    'Critical Care NP',
    'Family/Primary Care NP',
    'Neonatal NP',
    'Neonatal Critical Care NP',
    'OBGYN/Womens Health NP',
    'Pediatrics NP',
    'Pediatrics Critical Care NP',
    'Psych/Mental Health NP',
    'NP, No Subspecialty Noted'
]

for col in np_count_cols:
    missing_shapes[col] = 0

# 7. Reorder columns to match final
missing_shapes = missing_shapes[['County', 'Shape'] + np_count_cols]

# 8. Append only the missing counties to final
final_df = pd.concat([final, missing_shapes], ignore_index=True)

# 9. Optional: sort by county
final_df = final_df.sort_values('County').reset_index(drop=True)

final_df

,County,Shape,NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted"
0,Appling,"POLYGON ((-82.36884 31.63103, -82.37141 31.631...",29,0,0,0,0,24,0,0,0,0,0,0,5
1,Atkinson,"POLYGON ((-82.76169 31.3643, -82.75965 31.3644...",4,0,0,0,0,3,0,0,0,0,0,0,1
2,Bacon,"POLYGON ((-82.31024 31.58953, -82.30719 31.587...",10,0,0,0,0,7,0,0,0,1,0,1,1
3,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",1,0,0,0,0,1,0,0,0,0,0,0,0
4,Baldwin,"POLYGON ((-83.26867 32.9587, -83.26318 32.9541...",64,0,1,0,0,39,0,0,2,0,0,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Wilcox,"POLYGON ((-83.27244 31.9648, -83.27152 31.9636...",5,0,1,0,0,4,0,0,0,0,0,0,0
156,Wilkes,"POLYGON ((-82.6497 33.60877, -82.65082 33.6091...",1,0,0,0,0,1,0,0,0,0,0,0,0
157,Wilkinson,"POLYGON ((-83.09295 32.6489, -83.15598 32.6186...",5,0,0,0,0,4,0,0,1,0,0,0,0
158,Worth,"POLYGON ((-83.9986 31.37518, -83.9978 31.44375...",15,0,0,0,0,15,0,0,0,0,0,0,0
159,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
# Remove any rows where County is NaN
final_df = final_df[final_df['County'].notna()].reset_index(drop=True)
final_df

,County,Shape,NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted"
0,Appling,"POLYGON ((-82.36884 31.63103, -82.37141 31.631...",29,0,0,0,0,24,0,0,0,0,0,0,5
1,Atkinson,"POLYGON ((-82.76169 31.3643, -82.75965 31.3644...",4,0,0,0,0,3,0,0,0,0,0,0,1
2,Bacon,"POLYGON ((-82.31024 31.58953, -82.30719 31.587...",10,0,0,0,0,7,0,0,0,1,0,1,1
3,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",1,0,0,0,0,1,0,0,0,0,0,0,0
4,Baldwin,"POLYGON ((-83.26867 32.9587, -83.26318 32.9541...",64,0,1,0,0,39,0,0,2,0,0,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Whitfield,"POLYGON ((-85.05045 34.62248, -85.05081 34.710...",191,13,8,0,2,135,1,2,3,6,0,6,15
155,Wilcox,"POLYGON ((-83.27244 31.9648, -83.27152 31.9636...",5,0,1,0,0,4,0,0,0,0,0,0,0
156,Wilkes,"POLYGON ((-82.6497 33.60877, -82.65082 33.6091...",1,0,0,0,0,1,0,0,0,0,0,0,0
157,Wilkinson,"POLYGON ((-83.09295 32.6489, -83.15598 32.6186...",5,0,0,0,0,4,0,0,1,0,0,0,0
158,Worth,"POLYGON ((-83.9986 31.37518, -83.9978 31.44375...",15,0,0,0,0,15,0,0,0,0,0,0,0

In [17]:
#merge population counts
georgia_pop = pd.read_csv("~/Downloads/aidatalab/georgia_pop.csv")
georgia_pop

,fips,pop2025,pop2020,state,stateCode,growthSince2020,name,county,slug,areaMi,densityMi,rank
0,13121,1096737,1069333,Georgia,GA,0.025627,Fulton County,Fulton County,georgia/fulton-county,527,2081.094877,1
1,13135,1016136,958378,Georgia,GA,0.060266,Gwinnett County,Gwinnett County,georgia/gwinnett-county,431,2357.624130,2
2,13067,793868,766383,Georgia,GA,0.035863,Cobb County,Cobb County,georgia/cobb-county,340,2334.905882,3
3,13089,772567,764630,Georgia,GA,0.010380,DeKalb County,DeKalb County,georgia/dekalb-county,268,2882.712687,4
4,13051,309915,295076,Georgia,GA,0.050289,Chatham County,Chatham County,georgia/chatham-county,433,715.739030,5
...,...,...,...,...,...,...,...,...,...,...,...,...
154,13061,2761,2829,Georgia,GA,-0.024037,Clay County,Clay County,georgia/clay-county,195,14.158974,155
155,13007,2714,2850,Georgia,GA,-0.047719,Baker County,Baker County,georgia/baker-county,342,7.935673,156
156,13239,2368,2224,Georgia,GA,0.064748,Quitman County,Quitman County,georgia/quitman-county,151,15.682119,157
157,13307,2263,2352,Georgia,GA,-0.037840,Webster County,Webster County,georgia/webster-county,210,10.776190,158
158,13265,1639,1558,Georgia,GA,0.051990,Taliaferro County,Taliaferro County,georgia/taliaferro-county,195,8.405128,159

In [18]:
fips = pd.read_csv("~/Downloads/aidatalab/GA_FIPS.csv")
fips['FIPS Code'] = fips['FIPS Code'].astype(str)
fips

    FIPS Code County Name
0       13001     Appling
1       13003    Atkinson
2       13005       Bacon
3       13007       Baker
4       13009     Baldwin
..        ...         ...
154     13313   Whitfield
155     13315      Wilcox
156     13317      Wilkes
157     13319   Wilkinson
158     13321       Worth

[159 rows x 2 columns]

In [19]:
fips_map = fips.set_index('FIPS Code')['County Name'].to_dict()
georgia_pop['fips'] = georgia_pop['fips'].astype(str).str.zfill(5)
fips['FIPS Code'] = fips['FIPS Code'].astype(str).str.zfill(5)
georgia_pop['County'] = georgia_pop['fips'].map(fips_map)
georgia_pop

,fips,pop2025,pop2020,state,stateCode,growthSince2020,name,county,slug,areaMi,densityMi,rank,County
0,13121,1096737,1069333,Georgia,GA,0.025627,Fulton County,Fulton County,georgia/fulton-county,527,2081.094877,1,Fulton
1,13135,1016136,958378,Georgia,GA,0.060266,Gwinnett County,Gwinnett County,georgia/gwinnett-county,431,2357.624130,2,Gwinnett
2,13067,793868,766383,Georgia,GA,0.035863,Cobb County,Cobb County,georgia/cobb-county,340,2334.905882,3,Cobb
3,13089,772567,764630,Georgia,GA,0.010380,DeKalb County,DeKalb County,georgia/dekalb-county,268,2882.712687,4,De Kalb
4,13051,309915,295076,Georgia,GA,0.050289,Chatham County,Chatham County,georgia/chatham-county,433,715.739030,5,Chatham
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,13061,2761,2829,Georgia,GA,-0.024037,Clay County,Clay County,georgia/clay-county,195,14.158974,155,Clay
155,13007,2714,2850,Georgia,GA,-0.047719,Baker County,Baker County,georgia/baker-county,342,7.935673,156,Baker
156,13239,2368,2224,Georgia,GA,0.064748,Quitman County,Quitman County,georgia/quitman-county,151,15.682119,157,Quitman
157,13307,2263,2352,Georgia,GA,-0.037840,Webster County,Webster County,georgia/webster-county,210,10.776190,158,Webster
158,13265,1639,1558,Georgia,GA,0.051990,Taliaferro County,Taliaferro County,georgia/taliaferro-county,195,8.405128,159,Taliaferro

In [20]:
final_df = final_df.merge(
    georgia_pop[['County', 'pop2025']], 
    left_on='County', 
    right_on='County', 
    how='left'
)
final_df

,County,Shape,NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted",pop2025
0,Appling,"POLYGON ((-82.36884 31.63103, -82.37141 31.631...",29,0,0,0,0,24,0,0,0,0,0,0,5,18821
1,Atkinson,"POLYGON ((-82.76169 31.3643, -82.75965 31.3644...",4,0,0,0,0,3,0,0,0,0,0,0,1,8519
2,Bacon,"POLYGON ((-82.31024 31.58953, -82.30719 31.587...",10,0,0,0,0,7,0,0,0,1,0,1,1,10950
3,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",1,0,0,0,0,1,0,0,0,0,0,0,0,2714
4,Baldwin,"POLYGON ((-83.26867 32.9587, -83.26318 32.9541...",64,0,1,0,0,39,0,0,2,0,0,14,8,43865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Whitfield,"POLYGON ((-85.05045 34.62248, -85.05081 34.710...",191,13,8,0,2,135,1,2,3,6,0,6,15,105993
155,Wilcox,"POLYGON ((-83.27244 31.9648, -83.27152 31.9636...",5,0,1,0,0,4,0,0,0,0,0,0,0,9007
156,Wilkes,"POLYGON ((-82.6497 33.60877, -82.65082 33.6091...",1,0,0,0,0,1,0,0,0,0,0,0,0,9582
157,Wilkinson,"POLYGON ((-83.09295 32.6489, -83.15598 32.6186...",5,0,0,0,0,4,0,0,1,0,0,0,0,8587
158,Worth,"POLYGON ((-83.9986 31.37518, -83.9978 31.44375...",15,0,0,0,0,15,0,0,0,0,0,0,0,20253

In [21]:
#new col for density calculation
final_df['NP Density Per 10,000 Residents'] = (final_df['NP Count'] / final_df['pop2025']) * 1000
final_df

,County,Shape,NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted",pop2025,"NP Density Per 10,000 Residents"
0,Appling,"POLYGON ((-82.36884 31.63103, -82.37141 31.631...",29,0,0,0,0,24,0,0,0,0,0,0,5,18821,1.540832
1,Atkinson,"POLYGON ((-82.76169 31.3643, -82.75965 31.3644...",4,0,0,0,0,3,0,0,0,0,0,0,1,8519,0.469539
2,Bacon,"POLYGON ((-82.31024 31.58953, -82.30719 31.587...",10,0,0,0,0,7,0,0,0,1,0,1,1,10950,0.913242
3,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",1,0,0,0,0,1,0,0,0,0,0,0,0,2714,0.368460
4,Baldwin,"POLYGON ((-83.26867 32.9587, -83.26318 32.9541...",64,0,1,0,0,39,0,0,2,0,0,14,8,43865,1.459022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Whitfield,"POLYGON ((-85.05045 34.62248, -85.05081 34.710...",191,13,8,0,2,135,1,2,3,6,0,6,15,105993,1.802006
155,Wilcox,"POLYGON ((-83.27244 31.9648, -83.27152 31.9636...",5,0,1,0,0,4,0,0,0,0,0,0,0,9007,0.555124
156,Wilkes,"POLYGON ((-82.6497 33.60877, -82.65082 33.6091...",1,0,0,0,0,1,0,0,0,0,0,0,0,9582,0.104362
157,Wilkinson,"POLYGON ((-83.09295 32.6489, -83.15598 32.6186...",5,0,0,0,0,4,0,0,1,0,0,0,0,8587,0.582276
158,Worth,"POLYGON ((-83.9986 31.37518, -83.9978 31.44375...",15,0,0,0,0,15,0,0,0,0,0,0,0,20253,0.740631

In [22]:
final_df = final_df.rename(columns={'pop2025': 'Population'})

final_df = final_df[['County',
                     'Shape',
                     'Population',
                     'NP Density Per 10,000 Residents',
                     'NP Count',
                     'Acute Care NP',
                     'Adult/Gero NP',
                     'Community/Occupational/School NP',
                     'Critical Care NP',
                     'Family/Primary Care NP',
                     'Neonatal NP',
                     'Neonatal Critical Care NP',
                     'OBGYN/Womens Health NP',
                     'Pediatrics NP',
                     'Pediatrics Critical Care NP',
                     'Psych/Mental Health NP',
                     'NP, No Subspecialty Noted'
              ]]
final_df

,County,Shape,Population,"NP Density Per 10,000 Residents",NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted"
0,Appling,"POLYGON ((-82.36884 31.63103, -82.37141 31.631...",18821,1.540832,29,0,0,0,0,24,0,0,0,0,0,0,5
1,Atkinson,"POLYGON ((-82.76169 31.3643, -82.75965 31.3644...",8519,0.469539,4,0,0,0,0,3,0,0,0,0,0,0,1
2,Bacon,"POLYGON ((-82.31024 31.58953, -82.30719 31.587...",10950,0.913242,10,0,0,0,0,7,0,0,0,1,0,1,1
3,Baker,"POLYGON ((-84.63968 31.32287, -84.63842 31.322...",2714,0.368460,1,0,0,0,0,1,0,0,0,0,0,0,0
4,Baldwin,"POLYGON ((-83.26867 32.9587, -83.26318 32.9541...",43865,1.459022,64,0,1,0,0,39,0,0,2,0,0,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Whitfield,"POLYGON ((-85.05045 34.62248, -85.05081 34.710...",105993,1.802006,191,13,8,0,2,135,1,2,3,6,0,6,15
155,Wilcox,"POLYGON ((-83.27244 31.9648, -83.27152 31.9636...",9007,0.555124,5,0,1,0,0,4,0,0,0,0,0,0,0
156,Wilkes,"POLYGON ((-82.6497 33.60877, -82.65082 33.6091...",9582,0.104362,1,0,0,0,0,1,0,0,0,0,0,0,0
157,Wilkinson,"POLYGON ((-83.09295 32.6489, -83.15598 32.6186...",8587,0.582276,5,0,0,0,0,4,0,0,1,0,0,0,0
158,Worth,"POLYGON ((-83.9986 31.37518, -83.9978 31.44375...",20253,0.740631,15,0,0,0,0,15,0,0,0,0,0,0,0

In [23]:
final_df.to_csv('final_df.csv', index=False)

## visualization

In [24]:
geo_county = final_df.copy()

In [25]:
type(geo_county.loc[0, "Shape"])

shapely.geometry.polygon.Polygon

In [26]:
from shapely.geometry import mapping
geo_county["Shape"] = final_df["Shape"].apply(mapping)
geo_county

,County,Shape,Population,"NP Density Per 10,000 Residents",NP Count,Acute Care NP,Adult/Gero NP,Community/Occupational/School NP,Critical Care NP,Family/Primary Care NP,Neonatal NP,Neonatal Critical Care NP,OBGYN/Womens Health NP,Pediatrics NP,Pediatrics Critical Care NP,Psych/Mental Health NP,"NP, No Subspecialty Noted"
0,Appling,"{'type': 'Polygon', 'coordinates': (((-82.3688...",18821,1.540832,29,0,0,0,0,24,0,0,0,0,0,0,5
1,Atkinson,"{'type': 'Polygon', 'coordinates': (((-82.7616...",8519,0.469539,4,0,0,0,0,3,0,0,0,0,0,0,1
2,Bacon,"{'type': 'Polygon', 'coordinates': (((-82.3102...",10950,0.913242,10,0,0,0,0,7,0,0,0,1,0,1,1
3,Baker,"{'type': 'Polygon', 'coordinates': (((-84.6396...",2714,0.368460,1,0,0,0,0,1,0,0,0,0,0,0,0
4,Baldwin,"{'type': 'Polygon', 'coordinates': (((-83.2686...",43865,1.459022,64,0,1,0,0,39,0,0,2,0,0,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Whitfield,"{'type': 'Polygon', 'coordinates': (((-85.0504...",105993,1.802006,191,13,8,0,2,135,1,2,3,6,0,6,15
155,Wilcox,"{'type': 'Polygon', 'coordinates': (((-83.2724...",9007,0.555124,5,0,1,0,0,4,0,0,0,0,0,0,0
156,Wilkes,"{'type': 'Polygon', 'coordinates': (((-82.6497...",9582,0.104362,1,0,0,0,0,1,0,0,0,0,0,0,0
157,Wilkinson,"{'type': 'Polygon', 'coordinates': (((-83.0929...",8587,0.582276,5,0,0,0,0,4,0,0,1,0,0,0,0
158,Worth,"{'type': 'Polygon', 'coordinates': (((-83.9986...",20253,0.740631,15,0,0,0,0,15,0,0,0,0,0,0,0

In [27]:
#14467-14456 = 11
#lost 11 from them being in different states LOL
geo_county["NP Count"].sum()

np.int64(14456)

In [28]:
#convert to geo_json
import json

geojson = {
    "type": "FeatureCollection",
    "features": []
}

for _, row in final_df.iterrows():
    feature = {
        "type": "Feature",
        "geometry": row["Shape"],     # already in GeoJSON dict form
        "properties": {
            "County": row["County"]
        }
    }
    geojson["features"].append(feature)

#define specialties
specialties = [
    "NP Density",
    "NP Count",
    "Acute Care NP",
    "Adult/Gero NP",
    "Community/Occupational/School NP",
    "Critical Care NP",
    "Family/Primary Care NP",
    "Neonatal NP",
    "Neonatal Critical Care NP",
    "OBGYN/Womens Health NP",
    "Pediatrics NP",
    "Pediatrics Critical Care NP",
    "Psych/Mental Health NP",
    "NP No Subspecialty Noted"
]

In [31]:
import dash
from dash import dcc, html, Input, Output
import plotly.express as px

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Georgia NP Density & Specialty Map"),

    # Dropdown to select specialty
    dcc.Dropdown(
        id="specialty-dropdown",
        options=[{"label": s, "value": s} for s in specialties],
        value="NP Density",   # default
        clearable=False
    ),

    # Graph
    dcc.Graph(id="choropleth-map")
])

ModuleNotFoundError: No module named 'dash'